language: go
sudo: false
services:
  - postgresql
  - redis-server
go:
  - 1.9.3
before_install:
  # Setup dependency management tool
  - curl -L -s https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
install:
  - dep ensure
  - go get -u honnef.co/go/tools/cmd/staticcheck
  - go get -u honnef.co/go/tools/cmd/gosimple
  - go get -u github.com/kisielk/errcheck
before_script:
  - psql -c "CREATE DATABASE gorm;" -U postgres
  - psql -c "CREATE USER gorm WITH PASSWORD 'mypassword';" -U postgres
  - errcheck ./...
  - go fmt ./...
  - go vet ./...
  - gosimple ./...
script:
  - go test -i -race ./...
  - go test -v -race ./...